/* Cambios intencionales de la Fase 2 respecto al monolito de original/.
 *
 * La Fase 2 conecta la aplicación con Supabase. El archivo original/cambios-fase0.js
 * declara los cambios anteriores; este declara los de ahora, y build.js lee los dos.
 *
 * Igual que en la Fase 0, no se desactiva el control: build.js sigue exigiendo que
 * cada línea quitada o agregada esté aquí. Si algo cambia sin declararse, falla.
 *
 * Generado con el cálculo del multiconjunto de líneas y el diff del cuerpo del documento.
 * No editar a mano.
 */

module.exports = {
  cambios: [    {
      archivo: "js/nucleo/config-supabase.js",
      motivo: "Configuración de la nube generada desde supabase/.env.local: URL, anon key y tabla. La produce `npm run supabase:config`, no se edita a mano.",
      quita: [],
      agrega: ["const SUPABASE_URL='https://oinesldjexoxbkeljbbu.supabase.co';",
        "const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pbmVzbGRqZXhveGJrZWxqYmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyMjQxODUsImV4cCI6MjEwNjgwMDE4NX0.c0ciSmWPnANlSuX38D3_2COnYVz4Bct2DJNGOk4kKqc';",
        "const SUPABASE_TABLA='documentos';"],
    },
    {
      archivo: "js/nucleo/nube.js",
      motivo: "Motor de sincronización: subida agrupada 1,5 s tras cada cambio, hidratación al arrancar, detección de conflictos por rev, reset cloud y estados para la interfaz.",
      quita: [],
      agrega: ["const NUBE_ESPERA='espera';",
        "const NUBE_SIN='sin-conexion';",
        "const NUBE_LIMPIO='sincronizado';",
        "const NUBE_PENDIENTE='pendiente';",
        "const NUBE_SUBIENDO='subiendo';",
        "const NUBE_CONFLICTO='conflicto';",
        "const NUBE_ERROR='error';",
        "const NUBE_RETRASO=1500;",
        "let nubeEstado=NUBE_ESPERA;",
        "let nubeDetalle='';",
        "let nubeId=null;",
        "let nubeRev=0;",
        "let nubeSucio=false;",
        "let nubeConflicto=null;",
        "let nubeTemporizador=null;",
        "let nubeSubiendo=false;",
        "/* Durante la hidratación desde la nube se desactiva el marcado de pendiente: cargar un",
        " * documento remoto no es un cambio del usuario y no debe provocar una subida. */",
        "let nubeCallada=false;",
        "/* ── estado y avisos ─────────────────────────────────────────────────────── */",
        "const NUBE_TEXTOS={",
        "  [NUBE_ESPERA]:['Sin conectar','Aún no se ha intentado conectar con la nube.'],",
        "  [NUBE_SIN]:['Sin conexión','Los cambios se guardan en este dispositivo y se subirán al recuperar la red.'],",
        "  [NUBE_LIMPIO]:['Sincronizado','Este dispositivo está al día con la nube.'],",
        "  [NUBE_PENDIENTE]:['Guardando','Cambios pendientes de subir a la nube.'],",
        "  [NUBE_SUBIENDO]:['Subiendo','Enviando los cambios a la nube.'],",
        "  [NUBE_CONFLICTO]:['Conflicto sin resolver','Otro dispositivo guardó cambios mientras este estaba sin conexión.'],",
        "  [NUBE_ERROR]:['Error de nube','No se pudo sincronizar.'],",
        "};",
        "function nubeEstablecer(estado,detalle){",
        "  nubeEstado=estado;",
        "  if(detalle!==undefined)nubeDetalle=detalle;",
        "  nubePintar();",
        "}",
        "function nubeHayRed(){",
        "  if(typeof navigator!=='undefined'&&navigator.onLine===false)return false;",
        "  return true;",
        "}",
        "/* Copia del estado en el instante de subir. Sin esto, si el usuario sigue escribiendo",
        " * mientras la petición está en vuelo, se enviaría un documento inconsistente. */",
        "function nubeInstantanea(){return JSON.parse(JSON.stringify(db))}",
        "function nubePintar(){",
        "  const [titulo,detalle]=NUBE_TEXTOS[nubeEstado]||['—',''];",
        "  const e=$('nube-estado');",
        "  if(e)e.textContent=titulo;",
        "  const d=$('nube-detalle');",
        "  if(d)d.textContent=nubeDetalle||detalle;",
        "  const aviso=$('nube-aviso');",
        "  if(aviso)aviso.style.display=nubeEstado===NUBE_CONFLICTO?'':'none';",
        "  const at=$('nube-aviso-texto');",
        "  if(at)at.textContent=nubeEstado===NUBE_CONFLICTO",
        "    ?'Hay dos versiones del documento y ninguna se puede descartar sola. Elige cuál conservar.'",
        "    :'';",
        "  /* Mantenimiento refleja el estado real en vez de decir siempre «Operativa». */",
        "  const ms=$('ms-db-status');",
        "  if(ms)ms.textContent=nubeEstadoTexto();",
        "  const md=$('ms-db-detail');",
        "  if(md)md.textContent=nubeDetalleTexto();",
        "  const ns=$('ms-nube-status');",
        "  if(ns)ns.textContent=nubeEstadoTexto();",
        "  const nd=$('ms-nube-detail');",
        "  if(nd)nd.textContent=nubeDetalleTexto();",
        "  const nr=$('ms-nube-rev');",
        "  if(nr)nr.textContent=nubeRev?'r'+nubeRev:'—';",
        "}",
        "function nubeEstadoTexto(){",
        "  if(nubeEstado===NUBE_ESPERA)return'Sin conectar';",
        "  if(nubeEstado===NUBE_LIMPIO)return'Sincronizado';",
        "  if(nubeEstado===NUBE_SIN)return'Sin conexión';",
        "  if(nubeEstado===NUBE_PENDIENTE)return'Pendiente';",
        "  if(nubeEstado===NUBE_SUBIENDO)return'Subiendo';",
        "  if(nubeEstado===NUBE_CONFLICTO)return'Conflicto';",
        "  return'Error';",
        "}",
        "function nubeDetalleTexto(){",
        "  if(nubeDetalle)return nubeDetalle;",
        "  if(nubeEstado===NUBE_LIMPIO)return'Documento al día en la nube';",
        "  if(nubeEstado===NUBE_SIN)return'Los cambios se guardan aquí y se subirán al volver la red';",
        "  if(nubeEstado===NUBE_CONFLICTO)return'Otro dispositivo guardó cambios primero';",
        "  if(nubeEstado===NUBE_PENDIENTE)return'Esperando para subir';",
        "  if(nubeEstado===NUBE_SUBIENDO)return'Enviando cambios';",
        "  return'Aún no se ha conectado con la nube';",
        "}",
        "function nubeAviso(mensaje){",
        "  if(typeof notify==='function')notify(mensaje);",
        "}",
        "/* ── marcado de cambios pendientes ───────────────────────────────────────── */",
        "function nubeMarcarSucio(){",
        "  if(nubeCallada)return;",
        "  if(nubeEstado===NUBE_CONFLICTO)return;",
        "  nubeSucio=true;",
        "  // Se persiste en el acto, no al subir: así una pestaña cerrada a tiempo no pierde nada.",
        "  sbGuardarMeta({id:nubeId,rev:nubeRev,sucio:true});",
        "  if(nubeEstado!==NUBE_SUBIENDO)nubeEstablecer(NUBE_PENDIENTE);",
        "  nubeProgramar();",
        "}",
        "function nubeProgramar(){",
        "  if(nubeTemporizador)clearTimeout(nubeTemporizador);",
        "  nubeTemporizador=setTimeout(()=>{nubeTemporizador=null;nubeSubir()},NUBE_RETRASO);",
        "}",
        "/* ── subida ──────────────────────────────────────────────────────────────── */",
        "async function nubeSubir(){",
        "  if(nubeSubiendo||!nubeSucio)return;",
        "  /* El orden importa para el aviso que ve la persona. Antes se comprobaba `nubeId` y se",
        "   * salía sin decir nada, con lo que el panel se quedaba en «Guardando» para siempre",
        "   * cuando no había sesión. Ahora primero se averigua por qué no se puede subir. */",
        "  if(!nubeHayRed()){nubeEstablecer(NUBE_SIN);return}",
        "  if(!(await sbToken())){nubeEstablecer(NUBE_SIN,'sin sesión');return}",
        "  if(!nubeId){nubeEstablecer(NUBE_ESPERA,'todavía no hay documento en la nube');return}",
        "  nubeSubiendo=true;",
        "  nubeEstablecer(NUBE_SUBIENDO);",
        "  try{",
        "    const r=await sbGuardarDocumento(nubeInstantanea(),nubeRev,nubeId);",
        "    if(r.conflicto){",
        "      /* Otro dispositivo escribió primero. Se detiene todo: seguir insisting",
        "       * destruiría una de las dos versiones. */",
        "      try{nubeConflicto=await sbLeerDocumento()}catch(e){nubeConflicto=null}",
        "      nubeEstablecer(NUBE_CONFLICTO);",
        "      nubeAviso('Se detectaron cambios de otro dispositivo. Revisa Mantenimiento para elegir cuál conservar.');",
        "      return;",
        "    }",
        "    nubeRev=r.rev;",
        "    nubeSucio=false;",
        "    sbGuardarMeta({id:nubeId,rev:nubeRev,sucio:false});",
        "    nubeEstablecer(NUBE_LIMPIO);",
        "  }catch(e){",
        "    nubeEstablecer(sbEsFalloRed(e)?NUBE_SIN:NUBE_ERROR,e.message);",
        "    if(!sbEsFalloRed(e))console.error('Supabase: error al guardar',e);",
        "  }finally{",
        "    nubeSubiendo=false;",
        "  }",
        "}",
        "/* ── arranque ────────────────────────────────────────────────────────────── */",
        "/* Sustituye el estado en memoria por el de la nube. Se silencia el marcado de",
        " * pendientes porque aquí no hay ningún cambio del usuario. */",
        "function nubeHidratar(data){",
        "  nubeCallada=true;",
        "  try{",
        "    db=Object.assign(db,data||{});",
        "    normalizarDb();",
        "  }finally{",
        "    nubeCallada=false;",
        "  }",
        "}",
        "/**",
        " * Conecta, decide de quién es el documento y deja la app lista. Nunca lanza: si la",
        " * nube falla, la app arranca igual con los datos locales, que es justamente lo que",
        " * permite trabajar sin conexión.",
        " */",
        "async function nubeConectar(){",
        "  if(!(await sbToken())){nubeEstablecer(NUBE_SIN,'sin sesión');return}",
        "  if(!nubeHayRed()){nubeEstablecer(NUBE_SIN,'sin conexión al abrir');return}",
        "  let remoto=null;",
        "  try{",
        "    remoto=await sbLeerDocumento();",
        "  }catch(e){",
        "    nubeEstablecer(sbEsFalloRed(e)?NUBE_SIN:NUBE_ERROR,e.message);",
        "    return;",
        "  }",
        "  const meta=sbLeerMeta();",
        "  const pendiente=!!(meta&&meta.sucio);",
        "  const revConocido=meta?Number(meta.rev)||0:0;",
        "  /* Había cambios locales sin subir. Si además la nube está en otra versión, otro",
        "   * dispositivo escribió mientras este no tenía red: conflicto. */",
        "  if(pendiente&&remoto&&remoto.rev!==revConocido){",
        "    nubeId=remoto.id;",
        "    nubeRev=remoto.rev;",
        "    nubeConflicto=remoto;",
        "    nubeSucio=true;",
        "    nubeEstablecer(NUBE_CONFLICTO);",
        "    return;",
        "  }",
        "  /* Cambios locales pendientes y la nube sigue donde se dejó: se reenvían. Es la vía",
        "   * de recuperación de una subida que se interrumpió al cerrar la pestaña. */",
        "  if(pendiente){",
        "    try{",
        "      if(remoto){",
        "        const r=await sbGuardarDocumento(nubeInstantanea(),remoto.rev,remoto.id);",
        "        if(r.conflicto){nubeConflicto=remoto;nubeId=remoto.id;nubeRev=remoto.rev;nubeEstablecer(NUBE_CONFLICTO);return}",
        "        nubeId=remoto.id;",
        "        nubeRev=r.rev;",
        "      }else{",
        "        const c=await sbCrearDocumento(nubeInstantanea());",
        "        nubeId=c.id;",
        "        nubeRev=c.rev;",
        "      }",
        "      nubeSucio=false;",
        "      sbGuardarMeta({id:nubeId,rev:nubeRev,sucio:false});",
        "      nubeEstablecer(NUBE_LIMPIO);",
        "    }catch(e){",
        "      nubeEstablecer(sbEsFalloRed(e)?NUBE_SIN:NUBE_ERROR,e.message);",
        "    }",
        "    return;",
        "  }",
        "  /* Sin nada pendiente: la nube manda y se adopta su versión. */",
        "  if(remoto){",
        "    nubeId=remoto.id;",
        "    nubeRev=remoto.rev;",
        "    nubeSucio=false;",
        "    sbGuardarMeta({id:nubeId,rev:nubeRev,sucio:false});",
        "    nubeHidratar(remoto.data);",
        "    nubeEstablecer(NUBE_LIMPIO);",
        "    return;",
        "  }",
        "  /* Proyecto nuevo: se crea el documento con lo que haya en este dispositivo. */",
        "  try{",
        "    const c=await sbCrearDocumento(nubeInstantanea());",
        "    nubeId=c.id;",
        "    nubeRev=c.rev;",
        "    nubeSucio=false;",
        "    sbGuardarMeta({id:nubeId,rev:nubeRev,sucio:false});",
        "    nubeEstablecer(NUBE_LIMPIO);",
        "  }catch(e){",
        "    nubeEstablecer(sbEsFalloRed(e)?NUBE_SIN:NUBE_ERROR,e.message);",
        "  }",
        "}",
        "/* ── resolución de conflictos ────────────────────────────────────────────── */",
        "async function nubeResolver(modo){",
        "  const remoto=nubeConflicto;",
        "  if(!remoto)return;",
        "  if(modo==='nube'){",
        "    nubeHidratar(remoto.data);",
        "    persistirLocal();",
        "    nubeConflicto=null;",
        "    nubeSucio=false;",
        "    /* Sin esto el metadato local seguiría diciendo «pendiente» con el rev viejo: al",
        "     * arrancar otra vez, la app compararía ese rev contra el de la nube, vería que no",
        "     * cuadran y anunciaría un conflicto que ya está resuelto. */",
        "    sbGuardarMeta({id:nubeId,rev:nubeRev,sucio:false});",
        "    nubeEstablecer(NUBE_LIMPIO);",
        "    renderAllAfterDataChange();",
        "    nubeAviso('Se adoptó la versión de la nube.');",
        "    return;",
        "  }",
        "  /* Este dispositivo manda: se reescribe sobre el rev que hay ahora en la nube, no",
        "   * sobre el nuestro, porque el nuestro ya no existe. */",
        "  nubeId=remoto.id;",
        "  nubeRev=remoto.rev;",
        "  nubeConflicto=null;",
        "  nubeSucio=true;",
        "  sbGuardarMeta({id:nubeId,rev:nubeRev,sucio:true});",
        "  await nubeSubir();",
        "  renderAllAfterDataChange();",
        "}",
        "/* ── operaciones destructivas ────────────────────────────────────────────── */",
        "/** Vacía el documento en la nube y deja el de este dispositivo como nueva base. */",
        "async function nubeRestablecer(){",
        "  if(nubeId){",
        "    try{await sbBorrarDocumento(nubeId)}catch(e){",
        "      if(!sbEsFalloRed(e)){nubeAviso('No se pudo borrar en la nube: '+(e.message||e));return false}",
        "    }",
        "  }",
        "  nubeConflicto=null;",
        "  try{",
        "    const c=await sbCrearDocumento(nubeInstantanea());",
        "    nubeId=c.id;",
        "    nubeRev=c.rev;",
        "    nubeSucio=false;",
        "    sbGuardarMeta({id:nubeId,rev:nubeRev,sucio:false});",
        "    nubeEstablecer(NUBE_LIMPIO);",
        "    return true;",
        "  }catch(e){",
        "    nubeEstablecer(sbEsFalloRed(e)?NUBE_SIN:NUBE_ERROR,e.message);",
        "    return false;",
        "  }",
        "}",
        "/** Tras restaurar una copia local hay que subirla, o la nube la pisaría al siguiente",
        " *  arranque con la versión anterior. Como el usuario ha elegido esos datos",
        " *  explícitamente, se fuerza la subida aunque hubiera un conflicto pendiente. */",
        "async function nubeSubirRestauracion(){",
        "  nubeConflicto=null;",
        "  if(nubeId){",
        "    nubeSucio=true;",
        "    await nubeSubir();",
        "    return;",
        "  }",
        "  await nubeConectar();",
        "}",
        "/* Al recuperar la red se reintenta lo pendiente: guardar el cambio mientras no hay",
        " * conexión es el caso normal, no una excepción. */",
        "if(typeof window!=='undefined'){",
        "  window.addEventListener('online',()=>{if(nubeSucio)nubeSubir()});",
        "}",
        "}",
        "}",
        "}"],
    },
    {
      archivo: "js/nucleo/supabase.js",
      motivo: "Cliente REST de Supabase sobre fetch: sesión en localStorage, token vigente, renovación con reintento tras un 401 y CRUD del documento con control de rev.",
      quita: [],
      agrega: ["const SB_SESION='moto_repuesto_sandy_sb_sesion_v1';",
        "const SB_META='moto_repuesto_sandy_sb_meta_v1';",
        "/* ── errores ────────────────────────────────────────────────────────────────",
        " * Se distinguen dos families porque la app reacciona distinto: un fallo de red",
        " * significa \"sigue trabajando sin conexión\", mientras que un 4xx significa que el",
        " * servidor rechazó la operación y reintentar solo no arregla nada. */",
        "function sbError(mensaje,estado,codigo,red){",
        "  const e=new Error(mensaje);",
        "  e.sbEstado=estado??null;",
        "  e.sbCodigo=codigo??null;",
        "  e.sbRed=!!red;",
        "  return e;",
        "}",
        "const sbEsFalloRed=(e)=>!!(e&&e.sbRed);",
        "/* ── sesión ────────────────────────────────────────────────────────────────",
        " * Se guarda en localStorage y no en memoria para que cerrar y reabrir la app no",
        " * obligue a volver a escribir la contraseña: el refresh token dura semanas. */",
        "function sbLeerSesion(){",
        "  try{const s=JSON.parse(localStorage.getItem(SB_SESION)||'null');return(s&&s.refresh_token&&s.user)?s:null}",
        "  catch(e){return null}",
        "}",
        "function sbGuardarSesion(s){try{localStorage.setItem(SB_SESION,JSON.stringify(s))}catch(e){console.error('Supabase: no se pudo guardar la sesión',e)}}",
        "function sbOlvidarSesion(){try{localStorage.removeItem(SB_SESION)}catch(e){}}",
        "/* El `exp` va en el payload del JWT, sin cifrar: solo se usa para saber cuándo",
        " * renovar, nunca para autorizar nada. El servidor es quien valida la firma. */",
        "function sbExpiracion(token){",
        "  try{",
        "    const p=JSON.parse(atob(String(token).split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));",
        "    return Number(p.exp||0)*1000;",
        "  }catch(e){return 0}",
        "}",
        "function sbTokenVigente(){",
        "  const s=sbLeerSesion();",
        "  if(!s)return null;",
        "  if(sbExpiracion(s.access_token)-Date.now()>60e3)return s.access_token;",
        "  return null;",
        "}",
        "/* ── peticiones ────────────────────────────────────────────────────────────",
        " * Una función para todo: así el manejo del token y el refresco no puede quedar",
        " * sentido en uno de los sitios y olvidado en otro. */",
        "async function sbPeticion(metodo,ruta,{token,cuerpo,prefiere,reintentar=true}={}){",
        "  const cab={",
        "    apikey:SUPABASE_ANON_KEY,",
        "    'Content-Type':'application/json',",
        "    Authorization:'Bearer '+(token||SUPABASE_ANON_KEY),",
        "  };",
        "  if(prefiere)cab.Prefer=prefiere;",
        "  let r;",
        "  try{",
        "    r=await fetch(SUPABASE_URL+ruta,{",
        "      method:metodo,headers:cab,",
        "      body:cuerpo===undefined?undefined:JSON.stringify(cuerpo),",
        "    });",
        "  }catch(e){",
        "    // fetch solo lanza cuando no hubo respuesta: no hay red, DNS, CORS o el",
        "    // navegador bloqueó la petición. No es un error del servidor.",
        "    throw sbError('sin conexión con Supabase: '+(e.message||e),null,null,true);",
        "  }",
        "  const texto=await r.text();",
        "  let datos=null;",
        "  try{datos=texto?JSON.parse(texto):null}catch(e){datos=texto}",
        "  if(r.ok)return{estado:r.status,datos};",
        "  const codigo=datos&&typeof datos==='object'?datos.code:null;",
        "  /* 401 con refresh token: se renueva y se repite una sola vez, para no entrar en",
        "   * bucle si el refresh también falla. */",
        "  if(r.status===401&&reintentar&&sbLeerSesion()){",
        "    const s=sbLeerSesion();",
        "    const nuevo=await sbRenovar(s.refresh_token);",
        "    if(nuevo){sbGuardarSesion(nuevo);return sbPeticion(metodo,ruta,{token:nuevo.access_token,cuerpo,prefiere,reintentar:false})}",
        "  }",
        "  throw sbError(`Supabase respondió ${r.status}${codigo?' ('+codigo+')':''}: ${datos?.message||datos||''}`,r.status,codigo,false);",
        "}",
        "/* ── autenticación ───────────────────────────────────────────────────────── */",
        "async function sbRenovar(refresh_token){",
        "  if(!refresh_token)return null;",
        "  try{",
        "    const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{",
        "      method:'POST',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},",
        "      body:JSON.stringify({refresh_token}),",
        "    });",
        "    if(!r.ok)return null;",
        "    const d=await r.json();",
        "    if(!d.access_token)return null;",
        "    return{access_token:d.access_token,refresh_token:d.refresh_token||refresh_token,user:d.user||null};",
        "  }catch(e){return null}",
        "}",
        "/** Devuelve un token válido, renovándolo si hace falta. Null si no hay sesión. */",
        "async function sbToken(){",
        "  const directo=sbTokenVigente();",
        "  if(directo)return directo;",
        "  const s=sbLeerSesion();",
        "  if(!s)return null;",
        "  const nuevo=await sbRenovar(s.refresh_token);",
        "  if(!nuevo){sbOlvidarSesion();return null}",
        "  sbGuardarSesion(nuevo);",
        "  return nuevo.access_token;",
        "}",
        "async function sbIniciarSesion(correo,clave){",
        "  const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{",
        "    method:'POST',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},",
        "    body:JSON.stringify({email:correo,password:clave}),",
        "  });",
        "  const d=await r.json().catch(()=>null);",
        "  if(!r.ok){",
        "    const msg=/invalid login credentials/i.test(d?.error_description||d?.msg||'')",
        "      ?'Correo o contraseña incorrectos'",
        "      :(d?.msg||d?.error_description||('Supabase respondió '+r.status));",
        "    throw sbError(msg,r.status,d?.code??null,false);",
        "  }",
        "  const s={access_token:d.access_token,refresh_token:d.refresh_token,user:d.user||null};",
        "  sbGuardarSesion(s);",
        "  return s;",
        "}",
        "function sbCerrarSesion(){sbOlvidarSesion()}",
        "/* ── el documento ──────────────────────────────────────────────────────────",
        " * Un único documento JSONB por usuario. El `rev` lo incrementa solo la app, y cada",
        " * escritura se condiciona a `rev=eq.<rev que el cliente cree tener>`: si otro",
        " * dispositivo escribió mientras este estaba sin conexión, el PATCH no toca nada y",
        " * devuelve 0 filas. Eso convierte una pérdida de datos silenciosa en un aviso. */",
        "const SB_REST='/rest/v1/'+SUPABASE_TABLA;",
        "async function sbLeerDocumento(){",
        "  const token=await sbToken();",
        "  if(!token)throw sbError('sin sesión',401,'no_session',false);",
        "  const {datos}=await sbPeticion('GET',SB_REST+'?select=id,rev,data&limit=1',{token});",
        "  if(!Array.isArray(datos)||!datos.length)return null;",
        "  const f=datos[0];",
        "  return{id:f.id,rev:Number(f.rev)||1,data:f.data};",
        "}",
        "/** Crea el documento. Solo válido si no existe ninguno para este usuario. */",
        "async function sbCrearDocumento(data){",
        "  const token=await sbToken();",
        "  if(!token)throw sbError('sin sesión',401,'no_session',false);",
        "  const {datos}=await sbPeticion('POST',SB_REST+'?select=id,rev',{",
        "    token,prefiere:'return=representation',cuerpo:{data,rev:1},",
        "  });",
        "  const f=Array.isArray(datos)?datos[0]:null;",
        "  if(!f)throw sbError('el servidor no devolvió el documento creado',200,null,false);",
        "  return{id:f.id,rev:Number(f.rev)||1};",
        "}",
        "/** Guarda el estado. Devuelve {id,rev} al avanzar, o {conflicto:true} si otro",
        " *  dispositivo escribió antes: en ese caso el servidor NO ha modificado nada. */",
        "async function sbGuardarDocumento(data,rev,id){",
        "  const token=await sbToken();",
        "  if(!token)throw sbError('sin sesión',401,'no_session',false);",
        "  const siguiente=rev+1;",
        "  const ruta=SB_REST+'?id=eq.'+encodeURIComponent(id)+'&rev=eq.'+rev;",
        "  const {datos}=await sbPeticion('PATCH',ruta,{",
        "    token,prefiere:'return=representation',cuerpo:{data,rev:siguiente},",
        "  });",
        "  if(Array.isArray(datos)&&datos.length)return{id,rev:Number(datos[0].rev)||siguiente};",
        "  return{conflicto:true,rev};",
        "}",
        "async function sbBorrarDocumento(id){",
        "  const token=await sbToken();",
        "  if(!token)throw sbError('sin sesión',401,'no_session',false);",
        "  await sbPeticion('DELETE',SB_REST+'?id=eq.'+encodeURIComponent(id),{",
        "    token,prefiere:'return=representation',",
        "  });",
        "}",
        "/* ── metadatos locales de sincronización ─────────────────────────────────────",
        " * Guardar el `rev` conocido junto a la marca de \"pendiente\" es lo que permite",
        " * recuperar una escritura que no llegó a subirse: si al abrir la app el rev local es",
        " * mayor que el de la nube, se sabe que quedó algo sin enviar. */",
        "function sbLeerMeta(){",
        "  try{return JSON.parse(localStorage.getItem(SB_META)||'null')}catch(e){return null}",
        "}",
        "function sbGuardarMeta(m){",
        "  try{localStorage.setItem(SB_META,JSON.stringify(m))}catch(e){}",
        "}",
        "function sbOlvidarMeta(){try{localStorage.removeItem(SB_META)}catch(e){}}"],
    },
    {
      archivo: "js/ui/nube-acceso.js",
      motivo: "Capa de acceso: inicio de sesión, modo sin conexión, cierre de sesión y conexión inicial.",
      quita: [],
      agrega: ["function accesoMostrar(){",
        "  const c=$('capa-acceso');",
        "  if(c)c.classList.add('abierta');",
        "  const correo=$('acceso-correo');",
        "  if(correo)setTimeout(()=>correo.focus(),50);",
        "}",
        "function accesoOcultar(){",
        "  const c=$('capa-acceso');",
        "  if(c)c.classList.remove('abierta');",
        "  const e=$('acceso-error');",
        "  if(e)e.textContent='';",
        "}",
        "function accesoError(mensaje){",
        "  const e=$('acceso-error');",
        "  if(e)e.textContent=mensaje||'';",
        "}",
        "async function accesoEnviar(){",
        "  const correo=($('acceso-correo')?.value||'').trim();",
        "  const clave=$('acceso-clave')?.value||'';",
        "  if(!correo||!clave){accesoError('Escribe tu correo y contraseña.');return}",
        "  accesoError('Comprobando…');",
        "  try{",
        "    await sbIniciarSesion(correo,clave);",
        "    accesoOcultar();",
        "    await accesoConectar();",
        "  }catch(e){",
        "    /* Un fallo de red aquí NO es un problema del usuario: no se le pide que revise la",
        "     * contraseña si lo que falla es que no hay conexión. */",
        "    accesoError(sbEsFalloRed(e)?'No hay conexión con la nube. Puedes trabajar sin conexión con los datos de este dispositivo.':e.message);",
        "  }",
        "}",
        "function accesoSinConexion(){",
        "  accesoOcultar();",
        "  const s=sbLeerMeta();",
        "  if(s&&s.sucio)nubeAviso('Hay cambios sin subir. Se enviarán en cuanto vuelva la conexión.');",
        "}",
        "/** Cierra la sesión en este dispositivo. No borra nada: ni local ni en la nube. */",
        "function accesoSalir(){",
        "  if(typeof confirm==='function'&&!confirm('Se cerrará la sesión en este dispositivo. Los datos locales se conservan y los cambios pendientes dejarán de subirse hasta que vuelvas a entrar.'))return;",
        "  sbCerrarSesion();",
        "  sbOlvidarMeta();",
        "  nubeId=null;",
        "  nubeRev=0;",
        "  nubeSucio=false;",
        "  nubeConflicto=null;",
        "  nubeEstablecer(NUBE_SIN,'sesión cerrada en este dispositivo');",
        "  if(typeof renderMantenimiento==='function')renderMantenimiento();",
        "  accesoMostrar();",
        "}",
        "/** Tras entrar, conecta y adopta el documento de la nube si hay uno. */",
        "async function accesoConectar(){",
        "  const antes=nubeInstantanea();",
        "  await nubeConectar();",
        "  if(JSON.stringify(antes)!==JSON.stringify(db))renderAllAfterDataChange();",
        "  if(typeof renderMantenimiento==='function')renderMantenimiento();",
        "}",
        "/**",
        " * Punto de entrada del arranque. Devuelve `{hidratado:true}` si el documento venía de",
        " * la nube y difiere de lo que había en local, para que main.js sepa si debe repintar.",
        " *",
        " * Nunca lanza: si la nube no está disponible la app arranca igual con los datos",
        " * locales. Trabajar sin conexión es un modo de funcionamiento normal, no un error.",
        " */",
        "async function accesoNube(){",
        "  try{",
        "    if(!(await sbToken())){",
        "      accesoMostrar();",
        "      return null;",
        "    }",
        "    const antes=nubeInstantanea();",
        "    await nubeConectar();",
        "    return JSON.stringify(antes)!==JSON.stringify(db)?{hidratado:true}:null;",
        "  }catch(e){",
        "    console.error('Supabase: fallo al conectar, se sigue con los datos locales',e);",
        "    nubeEstablecer(NUBE_SIN,e.message);",
        "    return null;",
        "  }",
        "}"],
    },
    {
      archivo: "js/main.js",
      motivo: "El arranque pasa a ser asíncrono: primero se resuelve el acceso y la hidratación desde la nube, y después se pinta por primera vez.",
      quita: ["load();reestablecerSecuenciaGO();reajustarSecuenciaPPR();securitySettings();initDates();nav();initCxpSubnav();$('cxp-subnav')?.classList.remove('open');$('cxp-arrow')?.classList.remove('open');updateBrand();renderDashboard();renderGestion('contado');renderGestion('credito');renderGestion('recibos');renderCxp();renderGastos();renderNomina();renderCronograma();renderEmpresa();renderMantenimiento();copyLocalToIndexedDB(false);"],
      agrega: ["/* El arranque espera a la nube antes de pintar. El orden importa: si se pintara",
        " * primero y luego se descargara el documento, la primera vista mostraría los datos",
        " * locales y habría que redibujarla entera un instante después, con el riesgo de que un",
        " * clic en ese hueco editara la versión equivocada.",
        " *",
        " * Los datos locales se cargan ANTES de conectar porque son la respuesta inmediata y",
        " * además son la referencia que `accesoNube()` compara contra la nube para saber si",
        " * hubo que hidratar. */",
        "let arranque={hidratado:false};",
        "async function arrancar(){",
        "  load();",
        "  arranque=await accesoNube()||{hidratado:false};",
        "  reestablecerSecuenciaGO();reajustarSecuenciaPPR();securitySettings();initDates();nav();initCxpSubnav();$('cxp-subnav')?.classList.remove('open');$('cxp-arrow')?.classList.remove('open');updateBrand();renderDashboard();renderGestion('contado');renderGestion('credito');renderGestion('recibos');renderCxp();renderGastos();renderNomina();renderCronograma();renderEmpresa();renderMantenimiento();copyLocalToIndexedDB(false);",
        "arrancar();"],
    },
    {
      archivo: "js/nucleo/almacen.js",
      motivo: "save() y saveWithoutDrive() dejan el documento marcado como pendiente de subir. load() se parte en load() + normalizarDb() para poder reutilizar la normalización al restaurar una copia, sin releer localStorage.",
      quita: ["function load(){try{const x=localStorage.getItem(KEY);if(x)db=Object.assign(db,JSON.parse(x));}catch(e){};db.seriales=Object.assign({},db.seriales||{});db.empresa=Object.assign({nombre:'Moto Repuesto Sandy',margen:30},db.empresa||{});"],
      agrega: ["function save(){persistirLocal();idbPutState().catch(()=>{});scheduleDriveBackup();nubeMarcarSucio();}",
        "function saveWithoutDrive(){persistirLocal();idbPutState().catch(()=>{});nubeMarcarSucio()}",
        "/* Lectura de localStorage + normalización. La normalización va aparte porque al",
        " * arrancar puede haber dos fuentes: localStorage y el documento de Supabase. Ambas",
        " * dejan `db` en un estado válido solo pasando por aquí, y duplicar esas reglas de",
        " * saneado en el camino de la nube sería garantir que algún día se desincronizan. */",
        "function load(){try{const x=localStorage.getItem(KEY);if(x)db=Object.assign(db,JSON.parse(x));}catch(e){};normalizarDb();}",
        "function normalizarDb(){db.seriales=Object.assign({},db.seriales||{});db.empresa=Object.assign({nombre:'Moto Repuesto Sandy',margen:30},db.empresa||{});"],
      sustituye: ["function save(){persistirLocal();idbPutState().catch(()=>{});scheduleDriveBackup();}",
        "function saveWithoutDrive(){persistirLocal();idbPutState().catch(()=>{})}"],
    },
    {
      archivo: "js/nucleo/idb.js",
      motivo: "La recuperación de pagos de préstamos desde IndexedDB ya no se aplica sola: avisa y espera a que alguien la aplique a mano. Con la nube conectada, el documento del servidor manda y sobrescribirlo perdería datos reales.",
      quita: ["// Recuperación automática: si esta copia local perdió pagos de préstamos pero la copia",
        "// paralela de IndexedDB conserva una versión más completa, recuperamos esos datos.",
        "    if(savedPayments>localPayments && sameLoans){",
        "      db=Object.assign(db,saved);",
        "      notify('Datos de préstamos recuperados correctamente');"],
      agrega: ["// Recuperación de pagos de préstamos desde la copia de IndexedDB.",
        "//",
        "// Antes esta función sustituía `db` en cuanto el espejo tenía MÁS pagos que el",
        "// estado actual. Con la nube conectada eso es peligroso: el espejo local puede ser",
        "// viejo, y aplicarlo machacaría el documento que se acaba de descargar del servidor,",
        "// que es la fuente de verdad. Perder un pago guardado en otro dispositivo no es un",
        "// precio aceptable por una reparación automática.",
        "//",
        "// Ahora solo AVISA y deja que sea la persona quien decida. Si además la nube está",
        "// conectada, ni siquiera tiene sentido proponer nada: el servidor ya manda.",
        "    if(!(savedPayments>localPayments && sameLoans)) return;",
        "    if(nubeId){",
        "      notify('La copia local de IndexedDB tiene más pagos de préstamos, pero la nube está conectada: manda el documento del servidor.');",
        "      return;",
        "    const id='rec-idb-'+Date.now();",
        "    const caja=$('ms-rec-idb');",
        "    if(caja){",
        "      caja.style.display='';",
        "      $('ms-rec-idb-detalle').textContent=`La copia de IndexedDB tiene ${savedPayments} pagos de préstamos y el estado actual tiene ${localPayments}.`;",
        "    notify('Hay datos en IndexedDB que no están en el estado actual. Revísalo en Mantenimiento antes de aplicar nada.');",
        "/** Aplica a mano la copia de IndexedDB. Solo desde el botón, nunca al arrancar. */",
        "async function aplicarRecuperacionIndexedDB(){",
        "  try{",
        "    const snap=await idbGetState();",
        "    if(!snap?.data) return;",
        "    if(!confirm('Se reemplazarán los datos actuales por la copia de IndexedDB. Si la nube está conectada, esto se subirá a los demás dispositivos. ¿Continuar?')) return;",
        "    db=Object.assign(db,snap.data);",
        "    normalizarDb();",
        "    const caja=$('ms-rec-idb');",
        "    if(caja)caja.style.display='none';",
        "    notify('Datos de la copia de IndexedDB aplicados');",
        "  }catch(e){notify('No se pudo aplicar la copia de IndexedDB: '+(e.message||e))}"],
    },
    {
      archivo: "js/nucleo/respaldo.js",
      motivo: "Restaurar una copia llama a normalizarDb() en vez de a load(), que releía localStorage y deshacía la restauración en silencio; al terminar fuerza la subida. Restablecer datos borra además el documento de la nube, y Mantenimiento muestra el estado real de la sincronización en vez de una cadena fija.",
      quita: ["async function restoreBackupFile(e){const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(p.app!=='Moto Repuesto Sandy — Gestión Financiera'||!p.data||p.schema!=='moto_repuesto_sandy_backup_v1')throw new Error('El archivo no pertenece a este sistema.');if(p.sha256){const h=await sha256(JSON.stringify(p.data));if(h!==p.sha256)throw new Error('La copia no supera la verificación de integridad.')}const required=['gestionContado','gestionCredito','gestionRecibos','suplidores','facturasSuplidor','pagosSuplidor','gastos','acreedores','obligaciones','prestamos','pagosObligaciones','pagosPrestamos'];if(!required.every(k=>Array.isArray(p.data[k])))throw new Error('La estructura de la copia está incompleta.');if(!confirm('¿Restaurar esta copia? Los datos actuales serán reemplazados. Se recomienda tener una copia actual antes de continuar.'))return;db=Object.assign({empresa:{nombre:'Moto Repuesto Sandy',margen:30}},p.data);load();saveWithoutDrive();renderAllAfterDataChange();securitySettings().lastLocalBackup=new Date().toISOString();saveWithoutDrive();",
        "async function renderMantenimiento(){securitySettings();const st=databaseStats(),e=await localStorageEstimate();try{const r=await idbGetState();$('ms-idb-status').textContent=r?'Operativa — copia paralela':'Disponible — sin copia todavía';$('ms-idb-last').textContent=fmtDateTime(r?.savedAt)}catch(e){$('ms-idb-status').textContent='No disponible';$('ms-idb-last').textContent='—'}$('ms-db-status').textContent='Operativa';$('ms-db-detail').textContent=`${Object.keys(db).length} áreas de datos`;$('ms-db-size').textContent=bytesHuman(st.bytes);$('ms-db-quota').textContent=e.quota?`Cuota estimada: ${bytesHuman(e.quota)}`:'Cuota no disponible';$('ms-last-local').textContent=fmtDateTime(db.security.lastLocalBackup);$('ms-last-local-detail').textContent=db.security.lastIntegrity?`Integridad: ${fmtDateTime(db.security.lastIntegrity)}`:'Integridad: pendiente';$('ms-drive-status').textContent=db.security.driveFolder||'No conectado';$('ms-drive-detail').textContent=db.security.lastDriveBackup?`Última copia: ${fmtDateTime(db.security.lastDriveBackup)}`:'Sin copia en Drive';$('ms-auto-drive').value=db.security.autoDriveBackup?'si':'no';$('ms-retention').value=String(db.security.retention||30);['contado','credito','recibos','acreedores','facturas','prestamos','pagos','gastos'].forEach(k=>{const map={contado:st.contado,credito:st.credito,recibos:st.recibos,acreedores:st.acreedores,facturas:st.facturas,prestamos:st.prestamos,pagos:st.pagos,gastos:st.gastos};$('ms-n-'+k).value=map[k]});if($('ms-integrity')&&db.security.lastIntegrity==='')$('ms-integrity').innerHTML='Aún no se ha ejecutado la revisión.'}",
        "async function confirmResetData(){if(!confirm('ATENCIÓN: esto eliminará todos los datos operativos guardados en este navegador. ¿Crearás una copia antes de continuar?'))return;await downloadBackup('pre-reset');if(!confirm('Última confirmación: ¿realmente deseas dejar el sistema sin operaciones?'))return;db={empresa:Object.assign({nombre:'Moto Repuesto Sandy',margen:30},db.empresa||{}) ,gestionContado:[],gestionCredito:[],gestionRecibos:[],suplidores:[],facturasSuplidor:[],pagosSuplidor:[],gastos:[],empleados:[],nominas:[],acreedores:[],obligaciones:[],prestamos:[],pagosObligaciones:[],pagosPrestamos:[],seriales:{},security:Object.assign({autoDriveBackup:false,retention:30,lastLocalBackup:new Date().toISOString(),lastDriveBackup:'',lastIntegrity:''},db.security||{})};saveWithoutDrive();renderAllAfterDataChange();notify('Datos operativos restablecidos')}"],
      agrega: ["async function restoreBackupFile(e){const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(p.app!=='Moto Repuesto Sandy — Gestión Financiera'||!p.data||p.schema!=='moto_repuesto_sandy_backup_v1')throw new Error('El archivo no pertenece a este sistema.');if(p.sha256){const h=await sha256(JSON.stringify(p.data));if(h!==p.sha256)throw new Error('La copia no supera la verificación de integridad.')}const required=['gestionContado','gestionCredito','gestionRecibos','suplidores','facturasSuplidor','pagosSuplidor','gastos','acreedores','obligaciones','prestamos','pagosObligaciones','pagosPrestamos'];if(!required.every(k=>Array.isArray(p.data[k])))throw new Error('La estructura de la copia está incompleta.');if(!confirm('¿Restaurar esta copia? Los datos actuales serán reemplazados. Se recomienda tener una copia actual antes de continuar.'))return;/* Antes esto llamaba a load() justo después de asignar db, y load() relee localStorage:",
        " * devolvía el documento viejo y la restauración se deshacía sola, en silencio. Ahora solo",
        " * se normaliza lo que se acaba de asignar. */db=Object.assign({empresa:{nombre:'Moto Repuesto Sandy',margen:30}},p.data);normalizarDb();saveWithoutDrive();renderAllAfterDataChange();securitySettings().lastLocalBackup=new Date().toISOString();saveWithoutDrive();/* Se espera la subida: si la persona cierra la pestaña justo después de restaurar, sin await el PATCH se perdería y la nube volvería a pisar esos datos al próximo arranque. */await nubeSubirRestauracion();",
        "async function renderMantenimiento(){securitySettings();const st=databaseStats(),e=await localStorageEstimate();try{const r=await idbGetState();$('ms-idb-status').textContent=r?'Operativa — copia paralela':'Disponible — sin copia todavía';$('ms-idb-last').textContent=fmtDateTime(r?.savedAt)}catch(e){$('ms-idb-status').textContent='No disponible';$('ms-idb-last').textContent='—'}/* El estado de la nube lo escribe nube.js; aquí solo se reflete en el panel cuando ya",
        " * está resuelto. Se usaba una cadena fija ('Operativa') que mentía: la app podía llevar",
        " * horas sin conexión y el panel seguía diciendo que todo estaba bien. */",
        "const msd=$('ms-db-status');if(msd)msd.textContent=nubeEstadoTexto();const mdd=$('ms-db-detail');if(mdd)mdd.textContent=nubeDetalleTexto();const nds=$('ms-nube-status');if(nds)nds.textContent=nubeEstadoTexto();const ndd=$('ms-nube-detail');if(ndd)ndd.textContent=nubeDetalleTexto();const ndc=$('ms-nube-cuenta');if(ndc)ndc.textContent=sbLeerSesion()?'Conectado':'Sin sesión';const nde=$('ms-nube-email');if(nde)nde.textContent=sbLeerSesion()?.user?.email||'Entra para sincronizar';const ndr=$('ms-nube-rev');if(ndr)ndr.textContent=nubeRev?'r'+nubeRev:'—';$('ms-db-size').textContent=bytesHuman(st.bytes);$('ms-db-quota').textContent=e.quota?`Cuota estimada: ${bytesHuman(e.quota)}`:'Cuota no disponible';$('ms-last-local').textContent=fmtDateTime(db.security.lastLocalBackup);$('ms-last-local-detail').textContent=db.security.lastIntegrity?`Integridad: ${fmtDateTime(db.security.lastIntegrity)}`:'Integridad: pendiente';$('ms-drive-status').textContent=db.security.driveFolder||'No conectado';$('ms-drive-detail').textContent=db.security.lastDriveBackup?`Última copia: ${fmtDateTime(db.security.lastDriveBackup)}`:'Sin copia en Drive';$('ms-auto-drive').value=db.security.autoDriveBackup?'si':'no';$('ms-retention').value=String(db.security.retention||30);['contado','credito','recibos','acreedores','facturas','prestamos','pagos','gastos'].forEach(k=>{const map={contado:st.contado,credito:st.credito,recibos:st.recibos,acreedores:st.acreedores,facturas:st.facturas,prestamos:st.prestamos,pagos:st.pagos,gastos:st.gastos};$('ms-n-'+k).value=map[k]});if($('ms-integrity')&&db.security.lastIntegrity==='')$('ms-integrity').innerHTML='Aún no se ha ejecutado la revisión.'}",
        "async function confirmResetData(){if(!confirm('ATENCIÓN: esto eliminará todos los datos operativos guardados en este navegador y en la nube, por lo que desaparecerán también de tus otros dispositivos. ¿Crearás una copia antes de continuar?'))return;await downloadBackup('pre-reset');if(!confirm('Última confirmación: ¿realmente deseas dejar el sistema sin operaciones?'))return;db={empresa:Object.assign({nombre:'Moto Repuesto Sandy',margen:30},db.empresa||{}) ,gestionContado:[],gestionCredito:[],gestionRecibos:[],suplidores:[],facturasSuplidor:[],pagosSuplidor:[],gastos:[],empleados:[],nominas:[],acreedores:[],obligaciones:[],prestamos:[],pagosObligaciones:[],pagosPrestamos:[],seriales:{},security:Object.assign({autoDriveBackup:false,retention:30,lastLocalBackup:new Date().toISOString(),lastDriveBackup:'',lastIntegrity:''},db.security||{})};/* Restablecer solo lo local dejaría el documento de la nube intacto, y al siguiente",
        " * arranque la nube lo devolvería tal cual. Por eso se borra también allí y se crea uno",
        " * nuevo ya vacío. */saveWithoutDrive();await nubeRestablecer();renderAllAfterDataChange();notify('Datos operativos restablecidos')}"],
    },
    {
      archivo: "css/componentes.css",
      motivo: "Estilos de la capa de acceso a la nube y del mensaje de error al iniciar sesión.",
      quita: [],
      agrega: ["/*Accesoalanube.Capafijasobrelaapp:semuestrasolocuandonohaysesiónválida,demodoqueabrirlaappconlasesiónguardadanomolesta.*/.capa-acceso{display:none;position:fixed;inset:0;background:#0008;z-index:60;align-items:center;justify-content:center;padding:20px}",
        ".capa-acceso.abierta{display:flex}",
        ".capa-acceso.modal-box{max-width:380px}",
        ".acceso-error{color:#c0392b;margin-top:10px;min-height:18px}"],
    },
    {
      archivo: "index.html",
      motivo: "Añade la capa de acceso a la nube, el aviso de conflicto, el bloque de sincronización en Mantenimiento y el aviso de datos sin aplicar desde IndexedDB.",
      quita: ["<body>"],
      agrega: ["<body><divclass=\"capa-acceso\"id=\"capa-acceso\"><divclass=\"modal-box\"><divclass=\"section-title\">MotoRepuestoSandy</div><pclass=\"sub\"id=\"acceso-sub\">Entracontuusuarioparaquelosdatossesincronicenentretusdispositivos.</p><divclass=\"modal-grid\"><div><label>Correo</label><inputid=\"acceso-correo\"type=\"email\"autocomplete=\"username\"></div><div><label>Contraseña</label><inputid=\"acceso-clave\"type=\"password\"autocomplete=\"current-password\"onkeydown=\"if(event.key==='Enter')accesoEnviar()\"></div></div><buttonclass=\"btn\"style=\"margin-top:14px\"onclick=\"accesoEnviar()\">Entrar</button><pclass=\"acceso-error\"id=\"acceso-error\"></p><buttonclass=\"btnsecondary\"onclick=\"accesoSinConexion()\">Trabajarsinconexiónconlosdatosdeestedispositivo</button></div></div>"],
    },
    {
      archivo: "index.html",
      motivo: "Añade la capa de acceso a la nube, el aviso de conflicto, el bloque de sincronización en Mantenimiento y el aviso de datos sin aplicar desde IndexedDB.",
      quita: ["<mainclass=\"main\">"],
      agrega: ["<mainclass=\"main\"><divclass=\"cardno-print\"id=\"nube-aviso\"style=\"display:none\"><divclass=\"section-title\"id=\"nube-estado\">Nube</div><pid=\"nube-detalle\">—</p><pid=\"nube-aviso-texto\"style=\"margin:6px010px\">Haydosversionesdeldocumentoyningunasepuededescartarsola.Eligecuálconservar.</p><buttonclass=\"btn\"onclick=\"nubeResolver('nube')\">Conservarlaversióndelanube</button><buttonclass=\"btnsecondary\"onclick=\"nubeResolver('local')\">Conservarladeestedispositivo</button></div>"],
    },
    {
      archivo: "index.html",
      motivo: "Añade la capa de acceso a la nube, el aviso de conflicto, el bloque de sincronización en Mantenimiento y el aviso de datos sin aplicar desde IndexedDB.",
      quita: ["<divclass=\"cardno-print\"><divclass=\"section-title\">Estadodeseguridad</div>"],
      agrega: ["<divclass=\"cardno-print\"><divclass=\"section-title\">Sincronizaciónenlanube</div><divclass=\"kpis\"><divclass=\"kpi\"><span>Estado</span><bid=\"ms-nube-status\">—</b><smallid=\"ms-nube-detail\">—</small></div><divclass=\"kpi\"><span>Cuenta</span><bid=\"ms-nube-cuenta\">—</b><smallid=\"ms-nube-email\">—</small></div><divclass=\"kpi\"><span>Revisióndeldocumento</span><bid=\"ms-nube-rev\">—</b><small>Seincrementaconcadaguardado</small></div></div><divclass=\"modal-actions\"style=\"justify-content:flex-start;margin-top:10px\"><buttonclass=\"btnsecondary\"onclick=\"accesoSalir()\">Cerrarsesiónenestedispositivo</button><buttonclass=\"btnsecondary\"onclick=\"nubeSubir()\">Subircambiosahora</button></div></div><divclass=\"cardno-print\"><divclass=\"section-title\">Estadodeseguridad</div>"],
    },
    {
      archivo: "index.html",
      motivo: "Añade la capa de acceso a la nube, el aviso de conflicto, el bloque de sincronización en Mantenimiento y el aviso de datos sin aplicar desde IndexedDB.",
      quita: ["<pid=\"ms-drive-message\"class=\"note\"style=\"margin-top:10px\">PrimeroconectaunacarpetadeGoogleDriveparaescritorio.</p>"],
      agrega: ["<pid=\"ms-drive-message\"class=\"note\"style=\"margin-top:10px\">PrimeroconectaunacarpetadeGoogleDriveparaescritorio.</p><divclass=\"cardno-print\"id=\"ms-rec-idb\"style=\"display:none;margin-top:14px\"><divclass=\"section-title\">DatossinaplicardesdeIndexedDB</div><pclass=\"note\"id=\"ms-rec-idb-detalle\">—</p><pclass=\"note\">Noseaplicansolosapropósito:silanubeestáconectada,podríanmachacareldocumentodelservidor.</p><buttonclass=\"btnsecondary\"onclick=\"aplicarRecuperacionIndexedDB()\">Revisaryaplicar</button></div>"],
    },
  ],
};
