/* Cambios intencionales de la Fase 3 respecto al monolito de original/.
 *
 * La Fase 2 conecta la aplicación con Supabase. El archivo original/cambios-fase0.js
 * declara los cambios anteriores; este declara los de ahora, y build.js lee los dos.
 *
 * Igual que en la Fase 0, no se desactiva el control: build.js sigue exigiendo que
 * cada línea quitada o agregada esté aquí. Si algo cambia sin declararse, falla.
 *
 * Generado con el cálculo del multiconjunto de líneas y el diff del cuerpo del documento.
 * No editar a mano.
 */

module.exports = {
  cambios: [    {
      archivo: "js/nucleo/supabase.js",
      motivo: "Un fallo de red al iniciar sesión se convierte en un error de red legible en vez de propagarse como `TypeError`, para que la pantalla de acceso pueda ofrecer «Continuar sin conexión» en lugar de romperse.",
      quita: [],
      agrega: ["  /* No pasa por sbPeticion() porque aquí hace falta leer el estado y el cuerpo tal cual,",
        "   * pero el fallo de red hay que tratarlo igual que allí. Sin esto, entrar sin conexión",
        "   * tiraba el mensaje crudo del navegador (\"Failed to fetch\") en una pantalla en español y",
        "   * perdía el aviso de que se puede trabajar sin conexión. */",
        "    r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{",
        "    throw sbError('sin conexión con Supabase',null,null,true);",
        "}",
        "}",
        "}",
        "  try{",
        "  let r;",
        "  }catch(e){"],
      sustituye: ["  const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{",
        "    method:'POST',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},",
        "    body:JSON.stringify({email:correo,password:clave}),",
        "  });"],
    },
    {
      archivo: "js/ui/nube-acceso.js",
      motivo: "La capa de acceso pasa a ser una pantalla completa: muestra y oculta `#acceso`, alterna `acceso-activo` en el body, vacía la clave tras cada intento y añade el botón de mostrar contraseña.",
      quita: [],
      agrega: ["  const c=$('acceso');",
        "  /* La app se oculta por CSS con esta clase. Antes quedaba dibujada detrás del login, así",
        "   * que se podía tabular hasta el contenido con la pantalla de acceso abierta. */",
        "  document.body.classList.add('acceso-activo');",
        "  const c=$('acceso');",
        "  document.body.classList.remove('acceso-activo');",
        "  accesoClave(false);",
        "/** Muestra u oculta la contraseña. Un botón aparte se lee mejor que un icono pequeño, y",
        " *  al teclear en móvil no ayuda a recordar la clave. */",
        "function accesoVerClave(){",
        "  accesoClave(($('acceso-clave')?.type||'password')!=='text');",
        "function accesoClave(visible){",
        "  const c=$('acceso-clave');",
        "  if(!c)return;",
        "  c.type=visible?'text':'password';",
        "  const b=document.querySelector('.acceso-ver');",
        "  if(!b)return;",
        "  b.textContent=visible?'Ocultar':'Ver';",
        "  b.setAttribute('aria-pressed',String(visible));",
        "  b.setAttribute('aria-label',(visible?'Ocultar':'Mostrar')+' contraseña');"],
      sustituye: ["  const c=$('capa-acceso');",
        "  const c=$('capa-acceso');"],
    },
    {
      archivo: "css/base.css",
      motivo: "Tokens del tema: el crema cálido del fondo y los dorados de marca pasan a un gris frío con un único acento terracota, y `--gold` se renombra a `--accent` para que el nombre no mienta.",
      quita: [":root{--paper:#f7f5ef;--ink:#1c2430;--soft:#5c6675;--gold:#a8781f;--line:#dad4c4;--card:#fff;--green:#2f6f4e;--red:#a83232;--yellow:#b7791f;--blue:#35658d}",
        ".brandsmall{display:block;color:var(--gold);font:600.68rem-apple-system,sans-serif;margin-top:5px}",
        ".navbutton:hover,.navbutton.active{color:#fff;background:#ffffff0d;border-left-color:var(--gold)}",
        ".nav-sub{display:none;background:#141b24;border-left:3pxsolidvar(--gold);padding:4px06px}",
        ".nav-suba:hover{color:#fff;background:#ffffff0a;border-left-color:var(--gold)}"],
      agrega: [":root{--paper:#eff1f3;--ink:#1a2024;--soft:#5a646e;--accent:#c1502e;--accent-claro:#f0915e;--line:#d5dae0;--card:#fff;--green:#2f6f4e;--red:#a83232;--yellow:#b7791f;--blue:#35658d}",
        ".brandsmall{display:block;color:var(--accent-claro);font:600.68rem-apple-system,sans-serif;margin-top:5px}",
        ".navbutton:hover,.navbutton.active{color:#fff;background:#ffffff0d;border-left-color:var(--accent-claro)}",
        ".nav-sub{display:none;background:#141b24;border-left:3pxsolidvar(--accent-claro);padding:4px06px}",
        ".nav-suba:hover{color:#fff;background:#ffffff0a;border-left-color:var(--accent-claro)}"],
    },
    {
      archivo: "css/componentes.css",
      motivo: "La ventana de acceso se convierte en una pantalla completa con dos columnas en escritorio, botón de mostrar contraseña y perilaku offline; se retira el markup de la capa modal.",
      quita: ["input:focus,select:focus,textarea:focus{outline:2pxsolidvar(--gold);outline-offset:1px}",
        "td{padding:8px7px;border-bottom:1pxsolid#ede8dc;vertical-align:top}",
        ".formula{background:#faf8f1;border-left:4pxsolidvar(--gold);padding:12px14px;margin:12px0}",
        ".action-buttons.btn.secondary{border:0;background:#f4f4f4;color:var(--ink)}",
        ".action-buttons.btn.secondary:hover{background:#e9e9e9}",
        ".sem-head{display:flex;justify-content:space-between;padding:9px12px;background:#faf8f1;font-weight:700}"],
      agrega: ["input:focus,select:focus,textarea:focus{outline:2pxsolidvar(--accent);outline-offset:1px}",
        "td{padding:8px7px;border-bottom:1pxsolid#eaedf0;vertical-align:top}",
        ".formula{background:#f4f6f8;border-left:4pxsolidvar(--accent);padding:12px14px;margin:12px0}",
        ".action-buttons.btn.secondary{border:0;background:#f1f3f5;color:var(--ink)}",
        ".action-buttons.btn.secondary:hover{background:#e7eaee}",
        ".sem-head{display:flex;justify-content:space-between;padding:9px12px;background:#f4f6f8;font-weight:700}",
        "/*Accesoalanube—pantallacompleta,nounacajaflotante.**Antesestoeraunacapafijaconunaventanade380pxencimadelaapp.Eraun*fastidioendosformas:parecíaunaVentanadeerrorenlugardeunapantalla,ycomo*laappseguíadibujándosedetrássepodíatabularhastaelcontenidoconellogin*abierto.Ahoraocupalapantallayocultalaapp,asíqueloquehaydetrásniseveni*sealcanzaconelteclado.**Semuestrasolocuandonohaysesiónválida,demodoqueabrirlaappconlasesión*guardadasiguesiendotanrápidocomoantesdeañadirlanube.*/.acceso{display:none;background:var(--paper);color:var(--ink);padding:32px24px}",
        ".acceso.abierta{display:block}",
        "body.acceso-activo.app{display:none}",
        "/*dvhevitaelsaltodelhuecoinferiorenmóvilalabrirycerrareltecladovirtual;lalíneaenvheselrespaldoparalosquenolosoportan.*/.acceso-inner{max-width:880px;margin:0auto;min-height:100vh;min-height:100dvh;display:grid;grid-template-columns:1frminmax(300px,360px);gap:52px;align-items:center}",
        ".acceso-marca{max-width:32ch}",
        ".acceso-eyebrow{margin:0013px;font:700.7rem/1-apple-system,BlinkMacSystemFont,\"SegoeUI\",Roboto,sans-serif;letter-spacing:.17em;text-transform:uppercase;color:var(--accent)}",
        ".acceso-titulo{margin:0012px;font:4002.05rem/1.16Georgia,serif}",
        ".acceso-texto{margin:0;color:var(--soft);font-size:.94rem;line-height:1.55}",
        ".acceso-panel{border-left:1pxsolidvar(--line);padding-left:40px}",
        ".acceso-form{display:flex;flex-direction:column;gap:13px}",
        ".acceso-formlabel{margin-bottom:5px}",
        ".acceso-clave{display:flex;gap:8px}",
        ".acceso-claveinput{flex:1;min-width:0}",
        ".acceso-ver{flex:00auto;border:1pxsolidvar(--line);background:#fff;color:var(--soft);border-radius:4px;padding:013px;cursor:pointer;font:600.78rem-apple-system,BlinkMacSystemFont,\"SegoeUI\",Roboto,sans-serif}",
        ".acceso-ver:hover{color:var(--ink);border-color:#b9c0c8}",
        ".acceso-entrar{width:100%;margin:0;padding:12px;background:var(--accent);font-weight:700}",
        ".acceso-entrar:hover{background:#a94425}",
        ".acceso-error{color:var(--red);margin:0;font-size:.82rem;min-height:1.2em}",
        ".acceso-offline{margin-top:24px;padding-top:20px;border-top:1pxsolidvar(--line)}",
        ".acceso-offline.btn{margin:0;width:100%;padding:11px}",
        ".acceso-offline.note{margin:9px00;text-align:center}",
        "@media(max-width:760px){.acceso{padding:22px18px}.acceso-inner{grid-template-columns:1fr;gap:28px;align-content:center;padding:26px0}.acceso-marca{max-width:none}.acceso-titulo{font-size:1.65rem}.acceso-panel{border-left:0;padding-left:0;padding-top:24px;border-top:1pxsolidvar(--line)}}"],
      sustituye: ["/*Accesoalanube.Capafijasobrelaapp:semuestrasolocuandonohaysesiónválida,demodoqueabrirlaappconlasesiónguardadanomolesta.*/.capa-acceso{display:none;position:fixed;inset:0;background:#0008;z-index:60;align-items:center;justify-content:center;padding:20px}",
        ".capa-acceso.abierta{display:flex}",
        ".capa-acceso.modal-box{max-width:380px}",
        ".acceso-error{color:#c0392b;margin-top:10px;min-height:18px}"],
    },
    {
      archivo: "css/vistas.css",
      motivo: "Los tintes cálidos de superficies, tablas y avisos se neutran para acompañar el fondo frío sin cambiar la estructura.",
      quita: [".report-total-row{font-weight:700;border-top:2pxsolid#333;background:#f3efe3}",
        ".report-total-rowtd{padding-top:10px;padding-bottom:10px;background:#f3efe3}",
        ".phase-badge{display:inline-flex;width:25px;height:25px;align-items:center;justify-content:center;border-radius:50%;background:#eef2f5;color:var(--ink);font-weight:700;font-size:.78rem}",
        ".phase-panel{background:#faf8f1;border:1pxsolidvar(--line);border-radius:6px;padding:12px;margin:8px014px}",
        ".capture-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:8px;margin:10px0;background:#f3efe3;border:1pxsolidvar(--line);border-radius:6px;padding:10px}"],
      agrega: [".report-total-row{font-weight:700;border-top:2pxsolid#333;background:#edf0f3}",
        ".report-total-rowtd{padding-top:10px;padding-bottom:10px;background:#edf0f3}",
        ".phase-badge{display:inline-flex;width:25px;height:25px;align-items:center;justify-content:center;border-radius:50%;background:#e8edf2;color:var(--ink);font-weight:700;font-size:.78rem}",
        ".phase-panel{background:#f4f6f8;border:1pxsolidvar(--line);border-radius:6px;padding:12px;margin:8px014px}",
        ".capture-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:8px;margin:10px0;background:#edf0f3;border:1pxsolidvar(--line);border-radius:6px;padding:10px}"],
    },
    {
      archivo: "css/impresion.css",
      motivo: "La pantalla de acceso no debe aparecer en el papel.",
      quita: ["@mediaprint{body{background:#fff}.side,.no-print{display:none!important}.main{max-width:none;padding:0}.view{display:none!important}.view.printing{display:block!important}.print-only{display:block}.card{border:0;padding:0}.page-break{break-before:page}table{font-size:9pt}.kpi{break-inside:avoid}.print-report{display:block!important}}"],
      agrega: ["@mediaprint{body{background:#fff}.acceso{display:none!important}.side,.no-print{display:none!important}.main{max-width:none;padding:0}.view{display:none!important}.view.printing{display:block!important}.print-only{display:block}.card{border:0;padding:0}.page-break{break-before:page}table{font-size:9pt}.kpi{break-inside:avoid}.print-report{display:block!important}}"],
    },
    {
      archivo: "index.html",
      motivo: "Convierte el acceso a la nube en una pantalla completa, con formulario, aviso de error y salida sin conexión.",
      quita: ["divclass=\"capa-acceso\"id=\"capa-acceso\"><divclass=\"modal-box\"><divclass=\"section-title\">MotoRepuestoSandy</div><pclass=\"sub\"id=\"acceso-sub\">Entracontuusuarioparaquelosdatossesincronicenentretusdispositivos.</p><divclass=\"modal-grid\"><div><label>Correo</label><inputid=\"acceso-correo\"type=\"email\"autocomplete=\"username\"></div><div><label>Contraseña</label><inputid=\"acceso-clave\"type=\"password\"autocomplete=\"current-password\"onkeydown=\"if(event.key==='Enter')accesoEnviar()\"></div></div><buttonclass=\"btn\"style=\"margin-top:14px\"onclick=\"accesoEnviar()\">Entrar</button><pclass=\"acceso-error\"id=\"acceso-error\"></p><buttonclass=\"btnsecondary\"onclick=\"accesoSinConexion()\">Trabajarsinconexiónconlosdatosdeestedispositivo</button></div></div"],
      agrega: ["sectionclass=\"acceso\"id=\"acceso\"aria-labelledby=\"acceso-titulo\"><divclass=\"acceso-inner\"><divclass=\"acceso-marca\"><pclass=\"acceso-eyebrow\">MotoRepuestoSandy</p><h1class=\"acceso-titulo\"id=\"acceso-titulo\">Tusnúmeros,entodostusequipos.</h1><pclass=\"acceso-texto\">Entraparaquelacontabilidadsesincroniceentreeltaller,lacasaylaoficina.Quienentreenunequipovelomismoqueelresto.</p></div><divclass=\"acceso-panel\"><formclass=\"acceso-form\"id=\"acceso-form\"onsubmit=\"accesoEnviar();returnfalse\"novalidate><div><labelfor=\"acceso-correo\">Correo</label><inputid=\"acceso-correo\"type=\"email\"autocomplete=\"username\"autocapitalize=\"off\"spellcheck=\"false\"></div><div><labelfor=\"acceso-clave\">Contraseña</label><divclass=\"acceso-clave\"><inputid=\"acceso-clave\"type=\"password\"autocomplete=\"current-password\"><buttonclass=\"acceso-ver\"type=\"button\"onclick=\"accesoVerClave()\"aria-label=\"Mostrarcontraseña\"aria-pressed=\"false\">Ver</button></div></div><pclass=\"acceso-error\"id=\"acceso-error\"role=\"alert\"aria-live=\"polite\"></p><buttonclass=\"btnacceso-entrar\"type=\"submit\">Entrar</button></form><divclass=\"acceso-offline\"><buttonclass=\"btnsecondary\"type=\"button\"onclick=\"accesoSinConexion()\">Continuarsinconexión</button><pclass=\"note\">Loscambiosseguardaránenesteequipoysesubiráncuandovuelvasaentrar.</p></div></div></div></section"],
    },
  ],
};
