/* Respaldo — copia de seguridad, verificación de integridad y mantenimiento
 * Moto Repuesto Sandy — módulo extraído del monolito v18 v5.
 * Se carga como script clásico: comparte el scope global con el resto de módulos.
 */

function backupPayloadBase(){return {app:'Moto Repuesto Sandy — Gestión Financiera',schema:'moto_repuesto_sandy_backup_v1',createdAt:new Date().toISOString(),data:db}}

async function buildBackupPayload(){const p=backupPayloadBase();p.sha256=await sha256(JSON.stringify(p.data));return p}

function backupStamp(){return new Date().toISOString().replace(/[:.]/g,'-').replace(/Z$/,'')}

async function localStorageEstimate(){try{const e=await navigator.storage?.estimate?.();return e||{}}catch(e){return {}}}

function securitySettings(){db.security=Object.assign({autoDriveBackup:false,retention:30,lastLocalBackup:'',lastDriveBackup:'',lastIntegrity:''},db.security||{});return db.security}

async function downloadBackup(reason='manual'){const p=await buildBackupPayload(),blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`MotoRepuestoSandy_Backup_${backupStamp()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);securitySettings().lastLocalBackup=new Date().toISOString();saveWithoutDrive();renderMantenimiento();notify('Copia de seguridad descargada')}

async function restoreBackupFile(e){const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(p.app!=='Moto Repuesto Sandy — Gestión Financiera'||!p.data||p.schema!=='moto_repuesto_sandy_backup_v1')throw new Error('El archivo no pertenece a este sistema.');if(p.sha256){const h=await sha256(JSON.stringify(p.data));if(h!==p.sha256)throw new Error('La copia no supera la verificación de integridad.')}const required=['gestionContado','gestionCredito','gestionRecibos','suplidores','facturasSuplidor','pagosSuplidor','gastos','acreedores','obligaciones','prestamos','pagosObligaciones','pagosPrestamos'];if(!required.every(k=>Array.isArray(p.data[k])))throw new Error('La estructura de la copia está incompleta.');if(!confirm('¿Restaurar esta copia? Los datos actuales serán reemplazados. Se recomienda tener una copia actual antes de continuar.'))return;/* Antes esto llamaba a load() justo después de asignar db, y load() relee localStorage:
 * devolvía el documento viejo y la restauración se deshacía sola, en silencio. Ahora solo
 * se normaliza lo que se acaba de asignar. */db=Object.assign({empresa:{nombre:'Moto Repuesto Sandy',margen:30}},p.data);normalizarDb();saveWithoutDrive();renderAllAfterDataChange();securitySettings().lastLocalBackup=new Date().toISOString();saveWithoutDrive();/* Se espera la subida: si la persona cierra la pestaña justo después de restaurar, sin await el PATCH se perdería y la nube volvería a pisar esos datos al próximo arranque. */await nubeSubirRestauracion();
 recoverLoanDataFromIndexedDB();notify('Copia restaurada correctamente')}catch(err){notify('No se pudo restaurar: '+err.message)}finally{e.target.value=''}}

async function verifyDatabaseIntegrity(show=true){const errors=[],warnings=[],seen=new Set();const required=['gestionContado','gestionCredito','gestionRecibos','suplidores','facturasSuplidor','pagosSuplidor','gastos','acreedores','obligaciones','prestamos','pagosObligaciones','pagosPrestamos'];required.forEach(k=>{if(!Array.isArray(db[k]))errors.push(`Falta la colección ${k}`)});Object.entries(db).forEach(([k,v])=>{if(Array.isArray(v))v.forEach(x=>{if(x?.id){const key=k+':'+x.id;if(seen.has(key))errors.push(`ID duplicado en ${k}: ${x.id}`);seen.add(key)}if(x&&'saldo' in x&&Number(x.saldo)<-.004)errors.push(`Saldo negativo en ${k}`)})});db.facturasSuplidor.forEach(f=>{if(!db.suplidores.some(s=>s.id===f.suplidorId))warnings.push(`Factura ${f.codigo||''} sin suplidor válido`)});db.prestamos.forEach(p=>{if(Number(p.saldo)<-.004)errors.push(`Préstamo ${p.codigo||''} con saldo negativo`);if(!Array.isArray(p.cuotas))warnings.push(`Préstamo ${p.codigo||''} sin calendario de cuotas`)});const s=securitySettings(),now=new Date().toISOString();s.lastIntegrity=now;saveWithoutDrive();const box=$('ms-integrity');if(box){box.innerHTML=errors.length?`<b class="neg">Revisión con errores:</b> ${errors.join(' · ')}`:warnings.length?`<b class="warn">Integridad estructural correcta con advertencias:</b> ${warnings.join(' · ')}`:`<b class="pos">✓ Integridad estructural correcta.</b> No se encontraron inconsistencias críticas en las colecciones.`}if(show)notify(errors.length?'La revisión encontró errores':'Integridad verificada');renderMantenimiento();return {errors,warnings}}

async function requestPersistentStorage(){try{const ok=await navigator.storage?.persist?.();notify(ok?'El navegador concedió almacenamiento persistente.':'El navegador no concedió almacenamiento persistente.');renderMantenimiento()}catch(e){notify('No fue posible solicitar almacenamiento persistente')}}

async function renderMantenimiento(){securitySettings();const st=databaseStats(),e=await localStorageEstimate();try{const r=await idbGetState();$('ms-idb-status').textContent=r?'Operativa — copia paralela':'Disponible — sin copia todavía';$('ms-idb-last').textContent=fmtDateTime(r?.savedAt)}catch(e){$('ms-idb-status').textContent='No disponible';$('ms-idb-last').textContent='—'}/* El estado de la nube lo escribe nube.js; aquí solo se reflete en el panel cuando ya
 * está resuelto. Se usaba una cadena fija ('Operativa') que mentía: la app podía llevar
 * horas sin conexión y el panel seguía diciendo que todo estaba bien. */
const msd=$('ms-db-status');if(msd)msd.textContent=nubeEstadoTexto();const mdd=$('ms-db-detail');if(mdd)mdd.textContent=nubeDetalleTexto();const nds=$('ms-nube-status');if(nds)nds.textContent=nubeEstadoTexto();const ndd=$('ms-nube-detail');if(ndd)ndd.textContent=nubeDetalleTexto();const ndc=$('ms-nube-cuenta');if(ndc)ndc.textContent=sbLeerSesion()?'Conectado':'Sin sesión';const nde=$('ms-nube-email');if(nde)nde.textContent=sbLeerSesion()?.user?.email||'Entra para sincronizar';const ndr=$('ms-nube-rev');if(ndr)ndr.textContent=nubeRev?'r'+nubeRev:'—';$('ms-db-size').textContent=bytesHuman(st.bytes);$('ms-db-quota').textContent=e.quota?`Cuota estimada: ${bytesHuman(e.quota)}`:'Cuota no disponible';$('ms-last-local').textContent=fmtDateTime(db.security.lastLocalBackup);$('ms-last-local-detail').textContent=db.security.lastIntegrity?`Integridad: ${fmtDateTime(db.security.lastIntegrity)}`:'Integridad: pendiente';$('ms-drive-status').textContent=db.security.driveFolder||'No conectado';$('ms-drive-detail').textContent=db.security.lastDriveBackup?`Última copia: ${fmtDateTime(db.security.lastDriveBackup)}`:'Sin copia en Drive';$('ms-auto-drive').value=db.security.autoDriveBackup?'si':'no';$('ms-retention').value=String(db.security.retention||30);['contado','credito','recibos','acreedores','facturas','prestamos','pagos','gastos'].forEach(k=>{const map={contado:st.contado,credito:st.credito,recibos:st.recibos,acreedores:st.acreedores,facturas:st.facturas,prestamos:st.prestamos,pagos:st.pagos,gastos:st.gastos};$('ms-n-'+k).value=map[k]});if($('ms-integrity')&&db.security.lastIntegrity==='')$('ms-integrity').innerHTML='Aún no se ha ejecutado la revisión.'}

async function confirmResetData(){if(!confirm('ATENCIÓN: esto eliminará todos los datos operativos guardados en este navegador y en la nube, por lo que desaparecerán también de tus otros dispositivos. ¿Crearás una copia antes de continuar?'))return;await downloadBackup('pre-reset');if(!confirm('Última confirmación: ¿realmente deseas dejar el sistema sin operaciones?'))return;db={empresa:Object.assign({nombre:'Moto Repuesto Sandy',margen:30},db.empresa||{}) ,gestionContado:[],gestionCredito:[],gestionRecibos:[],suplidores:[],facturasSuplidor:[],pagosSuplidor:[],gastos:[],empleados:[],nominas:[],acreedores:[],obligaciones:[],prestamos:[],pagosObligaciones:[],pagosPrestamos:[],seriales:{},security:Object.assign({autoDriveBackup:false,retention:30,lastLocalBackup:new Date().toISOString(),lastDriveBackup:'',lastIntegrity:''},db.security||{})};/* Restablecer solo lo local dejaría el documento de la nube intacto, y al siguiente
 * arranque la nube lo devolvería tal cual. Por eso se borra también allí y se crea uno
 * nuevo ya vacío. */saveWithoutDrive();await nubeRestablecer();renderAllAfterDataChange();notify('Datos operativos restablecidos')}
