/* CxP — vista consolidada, navegación interna y selector de suplidor (F1)
 * Moto Repuesto Sandy — módulo extraído del monolito v18 v5.
 * Se carga como script clásico: comparte el scope global con el resto de módulos.
 */

function setCxpCurrent(id){
  document.querySelectorAll('#cxp-subnav a').forEach(a=>a.classList.toggle('active',a.dataset.cxpTarget===id));
  document.querySelectorAll('.cxp-title-current').forEach(el=>el.classList.remove('cxp-title-current'));
  const sec=document.getElementById(id);
  if(sec){
    const title=sec.querySelector('.section-title');
    if(title) title.classList.add('cxp-title-current');
  }
}

function getSuplidoresCxP(){return Array.isArray(db.suplidores)?db.suplidores.slice().sort((a,b)=>(a.codigo||'').localeCompare(b.codigo||'',undefined,{numeric:true})||a.nombre.localeCompare(b.nombre)):[]}

function seleccionarSuplidorCxP(id){const s=db.suplidores.find(x=>x.id===id);if(!s)return;const input=$('fx-tercero'),hid=$('fx-tercero-id'),sug=$('fx-suplidor-sugerencias');if(input){input.value=(s.codigo?s.codigo+' — ':'')+s.nombre;input.dataset.suplidorId=s.id}if(hid)hid.value='sup:'+s.id;if(sug)sug.style.display='none';renderCxp()}

function limpiarSuplidorCxP(){const input=$('fx-tercero'),hid=$('fx-tercero-id'),sug=$('fx-suplidor-sugerencias');if(input){input.value='';delete input.dataset.suplidorId}if(hid)hid.value='';if(sug)sug.style.display='none';renderCxp()}

function buscarSuplidorCxP(texto){const q=String(texto||'').trim().toLowerCase(),sug=$('fx-suplidor-sugerencias');if(!sug)return;if(!q){sug.style.display='none';if($('fx-tercero-id'))$('fx-tercero-id').value='';return}const arr=getSuplidoresCxP().filter(s=>(s.codigo||'').toLowerCase().includes(q)||(s.nombre||'').toLowerCase().includes(q));const exact=arr.find(s=>(s.codigo||'').toLowerCase()===q);if(exact){seleccionarSuplidorCxP(exact.id);return;}sug.innerHTML=arr.length?arr.slice(0,12).map(s=>`<button type="button" onclick="seleccionarSuplidorCxP('${s.id}')"><b>${s.codigo||'—'}</b> — ${esc(s.nombre)}</button>`).join(''):'<div style="padding:10px 12px;color:#777">No se encontró el suplidor.</div>';sug.style.display='block';}

function manejarF1Suplidor(e){const sug=$('fx-suplidor-sugerencias');const items=sug?[...sug.querySelectorAll('button')]:[];const active=sug?.querySelector('.active');if(e.key==='ArrowDown'){if(!items.length)return;e.preventDefault();let i=items.indexOf(active);i=i<0?0:(i+1)%items.length;items.forEach((b,n)=>b.classList.toggle('active',n===i));return}if(e.key==='ArrowUp'){if(!items.length)return;e.preventDefault();let i=items.indexOf(active);i=i<=0?items.length-1:i-1;items.forEach((b,n)=>b.classList.toggle('active',n===i));return}if(e.key==='Enter'){e.preventDefault();if(active){active.click();return}const q=String(e.target.value||'').trim().toLowerCase();const s=getSuplidoresCxP().find(x=>(x.codigo||'').toLowerCase()===q);if(s){seleccionarSuplidorCxP(s.id);return}const arr=getSuplidoresCxP().filter(x=>(x.codigo||'').toLowerCase().includes(q)||(x.nombre||'').toLowerCase().includes(q));if(arr.length===1)seleccionarSuplidorCxP(arr[0].id);}}

function mostrarSuplidoresCxP(){const old=$('supplier-modal-cxp');if(old)old.remove();const wrap=document.createElement('div');wrap.id='supplier-modal-cxp';wrap.className='supplier-modal-backdrop';wrap.innerHTML=`<div class="supplier-modal" role="dialog" aria-modal="true"><div class="supplier-modal-head"><b>Seleccionar suplidor</b><button type="button" class="btn secondary" onclick="cerrarSuplidoresCxP()">Cerrar</button></div><div class="supplier-modal-body"><input id="fx-suplidor-modal-busqueda" class="supplier-modal-search" placeholder="Buscar por código o nombre" oninput="filtrarModalSuplidoresCxP(this.value)"><div id="fx-suplidor-modal-lista"></div></div></div>`;document.body.appendChild(wrap);filtrarModalSuplidoresCxP('');setTimeout(()=>$('fx-suplidor-modal-busqueda')?.focus(),30);wrap.addEventListener('click',e=>{if(e.target===wrap)cerrarSuplidoresCxP()});}

function filtrarModalSuplidoresCxP(texto){const box=$('fx-suplidor-modal-lista');if(!box)return;const q=String(texto||'').trim().toLowerCase();const arr=getSuplidoresCxP().filter(s=>!q||(s.codigo||'').toLowerCase().includes(q)||(s.nombre||'').toLowerCase().includes(q));box.innerHTML=`<button type="button" class="supplier-list-btn" onclick="limpiarSuplidorCxP();cerrarSuplidoresCxP()"><span class="supplier-code">TODOS</span><span class="supplier-name">Todos los suplidores</span></button>`+(arr.length?arr.map(s=>`<button type="button" class="supplier-list-btn" onclick="seleccionarSuplidorCxP('${s.id}');cerrarSuplidoresCxP()"><span class="supplier-code">${esc(s.codigo||'—')}</span><span class="supplier-name">${esc(s.nombre)}</span></button>`).join(''):'<div style="padding:12px;color:#777">No hay suplidores que coincidan.</div>');}

function cerrarSuplidoresCxP(){const m=$('supplier-modal-cxp');if(m)m.remove();}

function seleccionarSuplidorCxPFiltro(valor){const hid=$('fx-tercero-id');if(hid)hid.value=valor||'';renderCxp()}

function resetCxpBusqueda(){if($('fx-tercero'))$('fx-tercero').value='';if($('fx-tercero-id'))$('fx-tercero-id').value='';if($('fx-modo'))$('fx-modo').value='corte';if($('fx-corte'))$('fx-corte').value=today();if($('fx-estado'))$('fx-estado').value='';if($('fx-suplidor-sugerencias'))$('fx-suplidor-sugerencias').style.display='none';toggleCxpFechas();renderCxp()}

function renderCxp(){if(limpiarObligacionesHuerfanas())save();fillAcreedores();fillCxpReportAcreedores();
 const tipo='suplidores',tercero=$('fx-tercero')?.value||$('fx-tercero-id')?.value||'',modo=$('fx-modo')?.value||'rango',desde=$('fx-desde')?.value||'',hasta=$('fx-hasta')?.value||'',corte=modo==='corte'?($('fx-corte')?.value||today()):'',filtro=$('fx-estado')?.value||'';
 const refDate=corte||hasta||today();
 const selectedSupplierId=tercero.startsWith('sup:')?tercero.slice(4):'';
 const suppliers=db.suplidores.filter(s=>!selectedSupplierId||selectedSupplierId===s.id).map(s=>({id:s.id,nombre:s.nombre,acreedorId:s.acreedorId}));
 const supplierRows= tipo!=='acreedores' ? db.facturasSuplidor.map(x=>{const sp=db.suplidores.find(q=>q.id===x.suplidorId),a=creditorById(x.acreedorId||sp?.acreedorId),saldo=balanceAsOfSupplier(x,corte);return {id:x.id,codigo:x.codigo,tipo:'Suplidor',nombre:sp?.nombre||a?.nombre||'—',documento:x.documento||'—',fecha:x.fecha,vencimiento:x.vencimiento,total:Number(x.total||0),saldo,estado:estadoFactura({saldo,vencimiento:x.vencimiento},refDate),dias:diasVencidosFirmados(x.vencimiento,refDate),credito:sp?.dias||a?.dias||0,kind:'factura'}}).filter(x=>!tercero||suppliers.some(sp=>sp.id===db.facturasSuplidor.find(f=>f.id===x.id)?.suplidorId)) : [];
 const obligationRows=tipo!=='suplidores' ? db.obligaciones.map(x=>({id:x.id,codigo:x.codigo,tipo:'Acreedor',nombre:creditorName(x.acreedorId),documento:x.codigo,fecha:x.fecha,vencimiento:x.vencimiento,total:Number(x.monto||0),saldo:balanceAsOfObligation(x,corte),estado:'',dias:diasVencidosFirmados(x.vencimiento,refDate),credito:daysBetween(x.fecha,x.vencimiento),kind:'obligacion',acreedorId:x.acreedorId})) : [];
 const loanRows=tipo!=='suplidores' ? db.prestamos.flatMap(p=>{const a=creditorById(p.acreedorId);const qs=(p.cuotas||[]).filter(q=>q.estado!=='Pagada'&&(!corte||q.fecha<=corte));return qs.map(q=>({id:p.id+'-'+q.numero,codigo:p.codigo+'-'+String(q.numero).padStart(2,'0'),tipo:'Acreedor',nombre:a?.nombre||'—',documento:p.codigo,fecha:p.fecha||q.fecha,vencimiento:q.fecha,total:Number(q.montoRestante??q.monto??0),saldo:balanceAsOfLoan(p,corte),estado:'',dias:diasVencidosFirmados(q.fecha,refDate),credito:daysBetween(p.fecha||q.fecha,q.fecha),kind:'prestamo',acreedorId:p.acreedorId,cuota:q.numero}));}) : [];
 const creditorRows=[...obligationRows,...loanRows];
 let rows=[...supplierRows,...creditorRows];
 if(tercero){if(tercero.startsWith('sup:')){const sid=tercero.slice(4);rows=rows.filter(x=>x.kind==='factura'&&db.facturasSuplidor.find(f=>f.id===x.id)?.suplidorId===sid);}else if(tercero.startsWith('acr:')){const aid=tercero.slice(4);rows=rows.filter(x=>x.acreedorId===aid);}}
 if(modo==='rango') rows=rows.filter(x=>inRange(x.fecha,desde,hasta)); else rows=rows.filter(x=>!corte||x.fecha<=corte);
 if(filtro) rows=rows.filter(x=>x.estado.toLowerCase()===filtro);
 rows=rows.filter(x=>x.saldo>.004 || filtro==='pagada').sort((a,b)=>(a.fecha||'').localeCompare(b.fecha||'')||(a.vencimiento||'').localeCompare(b.vencimiento||'')||(a.codigo||'').localeCompare(b.codigo||'',undefined,{numeric:true}));
 const daysCell=x=>{const d=Number(x.dias||0);const cls=d>0?'neg':'pos';return `<td class="r"><span class="days-status ${d>0?'red':'green'}"><b>${d}</b> ${Math.abs(d)===1?'día':'días'}</span></td>`};
 $('tbl-facturas-cxp').innerHTML=rows.length?rows.map(x=>`<tr><td>${x.codigo}</td><td>${x.tipo}</td><td>${x.nombre}</td><td>${x.documento}</td><td>${fmtDate(x.fecha)}</td><td>${fmtDate(x.vencimiento)}</td>${daysCell(x)}<td class="r">${money(x.total)}</td><td class="r">${money(x.saldo)}</td><td><span class="pill ${x.estado==='Vencida'?'red':x.estado==='Pagada'?'green':'yellow'}">${x.estado||'Pendiente'}</span></td><td class="no-print action-cell">${x.kind==='factura'?`<div class="action-buttons"><button class="btn secondary" onclick="openEditor('factura','${x.id}')">Editar</button><button class="btn secondary" onclick="printRecord('factura','${x.id}')">Imprimir</button></div>`:x.kind==='obligacion'?`<div class="action-buttons"><button class="btn secondary" onclick="openEditor('obligacion','${x.id}')">Editar</button><button class="btn secondary" onclick="printRecord('obligacion','${x.id}')">Imprimir</button></div>`:`<div class="action-buttons"><button class="btn secondary" onclick="printRecord('prestamo','${x.id.split('-')[0]}')">Imprimir</button></div>`}</td></tr>`).join(''):'<tr><td colspan="11" class="empty">No hay cuentas por pagar con los filtros seleccionados.</td></tr>';
 $('cxp-facturas-title').textContent='Recepción factura suplidor';
 $('fx-pend').textContent=money(rows.reduce((z,x)=>z+Number(x.saldo||0),0));$('fx-venc').textContent=money(rows.filter(x=>x.estado==='Vencida').reduce((z,x)=>z+Number(x.saldo||0),0));
 $('tbl-acreedores').innerHTML=db.acreedores.length?db.acreedores.map(a=>{const bs=db.facturasSuplidor.filter(f=>(f.acreedorId===a.id||db.suplidores.some(s=>s.id===f.suplidorId&&s.acreedorId===a.id))).reduce((z,f)=>z+Number(f.saldo||0),0);const bo=db.obligaciones.filter(o=>o.acreedorId===a.id&&obligacionVigente(o)).reduce((z,o)=>z+Number(o.saldo||0),0);const bp=db.prestamos.filter(p=>p.acreedorId===a.id).reduce((z,p)=>z+Number(p.saldo||0),0);return `<tr><td>${a.codigo}</td><td>${a.nombre}</td><td>${a.categoria}</td><td>${a.rnc||'—'}</td><td class="r">${money(bs+bo+bp)}</td><td class="no-print action-cell"><div class="action-buttons"><button class="btn secondary" onclick="openEditor('acreedor','${a.id}')">Editar</button><button class="btn secondary" onclick="printRecord('acreedor','${a.id}')">Imprimir</button></div></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">Sin acreedores.</td></tr>';
 $('tbl-prestamos').innerHTML=db.prestamos.length?db.prestamos.map(p=>{const original=Number(p.montoOriginal||0);const saldo=Number(p.saldo||0);const progreso=original>0?Math.min(100,Math.max(0,((original-saldo)/original)*100)):0;return `<tr><td>${p.codigo}</td><td>${creditorName(p.acreedorId)}</td><td class="r">${money(p.saldo)}</td><td>${money(p.cuota)}</td><td>#${p.proximaCuota||'—'}/${p.totalCuotas}</td><td>${fmtDate(p.proximoVencimiento)}</td><td>${progreso.toFixed(2)}%</td><td class="no-print action-cell"><div class="action-buttons"><button class="btn secondary" onclick="openEditor('prestamo','${p.id}')">Editar</button><button class="btn secondary" onclick="imprimirRecepcionPrestamo('${p.id}')">Recepción</button><button class="btn secondary" onclick="printRecord('prestamo','${p.id}')">Calendario</button></div></td></tr>`}).join(''):'<tr><td colspan="8" class="empty">Sin préstamos registrados.</td></tr>';
 fillControlCuotasPrestamo();
 renderPagosSp();renderFacturasPagoSp();renderHistorialPagos();renderHistorialGastos();fillCxpTerceros();toggleCxpFechas();
}
